url      = "http://127.0.0.1:9091/transmission/rpc"
username = "your-username"
password = "your-password"

theme = "tokyonight"
# theme = "catppuccin_mocha"
# theme = "dracula"
# theme = "gruvbox_dark"
# theme = "nord"
# theme = "rose_pine"
