[general]
background = "#1a1b26"
foreground = "#c0caf5"

[tabs]
active_fg = "#7aa2f7"
active_bg = "#24283b"
inactive_fg = "#565f89"
inactive_bg = "#1a1b26"
highlight = "#f7768e"

[table]
row_highlight_fg = "#24283b"
row_highlight_bg = "#7aa2f7"
